n = input('Digite algo: ')
print('o tipo primitivo desse valor é: ', type(n))
print('é numérico? ', n.isnumeric())
print('é somente alfabético? ', n.isalpha())
print('é alfanumerico? ',n.isalnum())
print('só tem espaço? ',n.isspace())
print('é decimal? ',n.isdecimal())
print('são letras maiusculas? ',n.isupper())
print('são letras minusculas? ',n.islower())